#ifndef _FELINE_H_
#define _FELINE_H_

#include"Animal.h"
/**
 * 
 * This is a subclass of Animal Class for Feline Animal Family
 *
 */
class Feline :public Animal
{
  public:

    /**
	 * A constructor to initialize Feline's name
	 * @param name -  Name of the Feline Animal
     @param type - Class name of the object  
	 */
    Feline(string name, string type);
    /**
	 * Function which tell Feline to run around
	 */
    void Roam();
    
};
/**
 * 
 * Class Lion which is a subclass of Feline Class
 *
 */

class Lion :public Feline
{
  public:
  /**
	 * A constructor to initialize Lion's name
	 * @param name Name of the Lion
	 */

    Lion(string name);
    /**
	 * A Function to get Lion make noise
	 */
    void MakeNoise();
};
/**
 * 
 * Class Tiger which is a subclass of Feline Class
 *
 */
class Tiger :public Feline
{
  public:
  /**
	 * A constructor to initialize Tiger's name
	 * @param name Name of the Tiger
	 */
    Tiger(string name);
    /**
	 * A function to get Tiger make noise
	 */
    void MakeNoise();
};
/**
 * 
 * Class Cat which is a subclass of Feline Class
 *
 */
class Cat :public Feline
{
  public:
  /**
	 * A constructor to initialize Cat's name
	 * @param name Name of the Cat
	 */
    Cat(string name);
    /**
	 * A function to get Cat make noise
	 */
    void MakeNoise();
    /**
	 * A function to put the cat on sleep
	 */
    void Sleep();
    /**
	 * A function to ask the Cat to roam
	 */
    void Roam();
    /**
	 * A function to wake up the Cat
	 */
    void WakeUp();
    /**
	 * Based on number generated by builtin rand, this method
	 * decides what cat will do
	 * 0- Make Noise
	 * 1- Sleep
	 * 2- Wakeup
	 * 3- Roam
	 * 4- Eat
	 */
    void RandomActivity();
    /**
	 * A function to ask the cat to eat
	 */
    void StartEat();
};
#endif