import java.util.Random;
/**
 * 
 * Class Cat which is a subclass of Feline Class
 *
 */

public class Cat extends Feline{
	
	/**
	 * A constructor to initialize Cat's name
	 * @param name Name of the Cat
	 */
	public Cat(String name)
	{
		super(name);
	}
	/**
	 * A method to get Cat make noise
	 */
	public void makeNoise() {
		
		this.RandomActivity();
	}
	
	/**
	 * A method to ask the cat to eat
	 */
	public void eat() {
		
		this.RandomActivity();
	}
	
	
	/**
	 * A method to put the cat on sleep
	 */
	public void sleep()
	{
		this.RandomActivity();
	}
	
	
	/**
	 * A method to wake up the Cat
	 */
	public void wakeUp() {
		
		this.RandomActivity();
	}
	
	/**
	 * A method to ask the Cat to roam
	 */
	public void roam() {
		
		this.RandomActivity();
	}
	
	/**
	 * To generate random number 
	 * @return 0-4  randomly
	 */
	
	public int RandomNumber()
	{
		Random random = new Random();
		return random.nextInt(5);
		
	}
	
	
	/**
	 * Based on number generated by RandomNumber method, this method
	 * decides what cat will do
	 * 0- Make Noise
	 * 1- Roam around
	 * 2- Sleep
	 * 3- Wakeup
	 * 4- Eat
	 */
	
	
	
	public void RandomActivity()
	{
		int randnum=RandomNumber();
		
		switch(randnum)
		{
			case 0: System.out.println(this.name+" is a "+this.getClass().getName() );
					System.out.println(this.name+" hissed");
					break;
		
			case 1:super.roam();
					break;
			case 2:super.sleep();
					break;
			case 3:super.wakeUp();
					break;
			case 4:super.eat();
					break;
					
			}
		
	}
	
	

}
