/**
 * 
 * Class Cat which is a subclass of Feline Class
 *
 */

public class Cat extends Feline{
	
	/**
	 * A constructor to initialize Cat's name
	 * @param name Name of the Cat
	 */
	public Cat(String name)
	{
		super(name);
	}
	/**
	 * A method to get Cat make noise
	 */
	public void makeNoise() {
		
		System.out.println(this.name+" is a "+this.getClass().getName() );
		System.out.println(this.name+" hissed");
	}
	/**
	 * To generate random number 
	 * @return 0,1 or 2 randomly
	 */
	
	public int RandomNumber()
	{
		return (int) (Math.random()*3);
		
	}
	
	/**
	 * Based on number generated by RandomNumber method, this method
	 * decides what cat will do
	 * 0- Make Noise
	 * 1- Roam around
	 * 2- Sleep
	 */
	public void sleep()
	{
		int randnum=RandomNumber();
		
		if(randnum==0)
			{this.makeNoise();
			return;
			}
		else if(randnum==1)
			{this.roam();
			return;
			}
		super.sleep();
	}

}
